app:
  name: backbase-jenkins 
  replicas: 1

image:
  repository: hygosr/backbase-jenkins 
  tag: 1.0.0
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 8085
  targetPort: 8080

resources: 
  limits:
    cpu: 512m
    memory: 1024Mi
  requests:
    cpu: 512m
    memory: 1024Mi
